import axios from 'axios';

const SENDGRID_API_KEY = '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';
const SENDGRID_URL = 'https://api.sendgrid.com/v3/mail/send';

export const sendEmail = async ({ to, subject, message }) => {
  const htmlTemplate = `
    <div style="font-family: sans-serif; padding: 20px; background-color: #f4f4f4;">
      <div style="max-width: 600px; margin: auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
        <h2 style="color: #e74c3c;">🚨 Emergency Alert</h2>
        <p>${message.replace(/\n/g, '<br/>')}</p>
        <br/>
        <p style="font-weight: bold;">Stay safe,<br/>Cura App ❤️</p>
        <hr style="margin: 20px 0;" />
        <p style="font-size: 12px; color: gray;">This message was generated by the Cura emergency alert system.</p>
      </div>
    </div>
  `;

  const data = {
    personalizations: [
      {
        to: [{ email: to }],
        subject: subject,
      },
    ],
    from: { email: 'ayuze86insask@gmail.com' },
    content: [
      {
        type: 'text/html', // ✅ send HTML instead of plain text
        value: htmlTemplate,
      },
    ],
  };

  try {
    const res = await axios.post(SENDGRID_URL, data, {
      headers: {
        Authorization: `Bearer ${SENDGRID_API_KEY}`,
        'Content-Type': 'application/json',
      },
    });

    console.log('✅ Email request accepted:', res.status); // should be 202
    return { success: true };
  } catch (err) {
    console.error('❌ SendGrid Error:', {
      message: err.message,
      response: err.response?.data,
      status: err.response?.status,
    });
    return { success: false, error: err.message };
  }
};
